package member.card.model;

import java.util.Date;

public class IntegralExchange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_exchange.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_exchange.integrla_id
     *
     * @mbggenerated
     */
    private Integer integrlaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_exchange.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_exchange.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_exchange.pic
     *
     * @mbggenerated
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_exchange.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral_exchange.Need_integral
     *
     * @mbggenerated
     */
    private Integer needIntegral;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    public IntegralExchange(Integer id, Integer integrlaId, String title, Date endTime, String pic, String introduction, Integer needIntegral) {
        this.id = id;
        this.integrlaId = integrlaId;
        this.title = title;
        this.endTime = endTime;
        this.pic = pic;
        this.introduction = introduction;
        this.needIntegral = needIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    public IntegralExchange() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_exchange.id
     *
     * @return the value of integral_exchange.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_exchange.id
     *
     * @param id the value for integral_exchange.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_exchange.integrla_id
     *
     * @return the value of integral_exchange.integrla_id
     *
     * @mbggenerated
     */
    public Integer getIntegrlaId() {
        return integrlaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_exchange.integrla_id
     *
     * @param integrlaId the value for integral_exchange.integrla_id
     *
     * @mbggenerated
     */
    public void setIntegrlaId(Integer integrlaId) {
        this.integrlaId = integrlaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_exchange.title
     *
     * @return the value of integral_exchange.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_exchange.title
     *
     * @param title the value for integral_exchange.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_exchange.end_time
     *
     * @return the value of integral_exchange.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_exchange.end_time
     *
     * @param endTime the value for integral_exchange.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_exchange.pic
     *
     * @return the value of integral_exchange.pic
     *
     * @mbggenerated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_exchange.pic
     *
     * @param pic the value for integral_exchange.pic
     *
     * @mbggenerated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_exchange.introduction
     *
     * @return the value of integral_exchange.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_exchange.introduction
     *
     * @param introduction the value for integral_exchange.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral_exchange.Need_integral
     *
     * @return the value of integral_exchange.Need_integral
     *
     * @mbggenerated
     */
    public Integer getNeedIntegral() {
        return needIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral_exchange.Need_integral
     *
     * @param needIntegral the value for integral_exchange.Need_integral
     *
     * @mbggenerated
     */
    public void setNeedIntegral(Integer needIntegral) {
        this.needIntegral = needIntegral;
    }
}