package member.card.model;

public class Integral {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.balance
     *
     * @mbggenerated
     */
    private Integer balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    public Integral(Integer id, Integer memberId, Integer balance) {
        this.id = id;
        this.memberId = memberId;
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    public Integral() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.id
     *
     * @return the value of integral.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.id
     *
     * @param id the value for integral.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.member_id
     *
     * @return the value of integral.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.member_id
     *
     * @param memberId the value for integral.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.balance
     *
     * @return the value of integral.balance
     *
     * @mbggenerated
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.balance
     *
     * @param balance the value for integral.balance
     *
     * @mbggenerated
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
}