package member.card.model;

import java.util.Date;

public class PayOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.money
     *
     * @mbggenerated
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.real_money
     *
     * @mbggenerated
     */
    private Long realMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.pay_num
     *
     * @mbggenerated
     */
    private String payNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.coupons_type
     *
     * @mbggenerated
     */
    private Integer couponsType;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbggenerated
     */
    public PayOrder(Integer id, Integer memberId, Integer businessId, Long money, Long realMoney, Date createTime, Short status, Integer payType, String payNum, Integer couponsType) {
        this.id = id;
        this.memberId = memberId;
        this.businessId = businessId;
        this.money = money;
        this.realMoney = realMoney;
        this.createTime = createTime;
        this.status = status;
        this.payType = payType;
        this.payNum = payNum;
        this.couponsType = couponsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order
     *
     * @mbggenerated
     */
    public PayOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.id
     *
     * @return the value of pay_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.id
     *
     * @param id the value for pay_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.member_id
     *
     * @return the value of pay_order.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.member_id
     *
     * @param memberId the value for pay_order.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.business_id
     *
     * @return the value of pay_order.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.business_id
     *
     * @param businessId the value for pay_order.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.money
     *
     * @return the value of pay_order.money
     *
     * @mbggenerated
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.money
     *
     * @param money the value for pay_order.money
     *
     * @mbggenerated
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.real_money
     *
     * @return the value of pay_order.real_money
     *
     * @mbggenerated
     */
    public Long getRealMoney() {
        return realMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.real_money
     *
     * @param realMoney the value for pay_order.real_money
     *
     * @mbggenerated
     */
    public void setRealMoney(Long realMoney) {
        this.realMoney = realMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.create_time
     *
     * @return the value of pay_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.create_time
     *
     * @param createTime the value for pay_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.status
     *
     * @return the value of pay_order.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.status
     *
     * @param status the value for pay_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.pay_type
     *
     * @return the value of pay_order.pay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.pay_type
     *
     * @param payType the value for pay_order.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.pay_num
     *
     * @return the value of pay_order.pay_num
     *
     * @mbggenerated
     */
    public String getPayNum() {
        return payNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.pay_num
     *
     * @param payNum the value for pay_order.pay_num
     *
     * @mbggenerated
     */
    public void setPayNum(String payNum) {
        this.payNum = payNum == null ? null : payNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.coupons_type
     *
     * @return the value of pay_order.coupons_type
     *
     * @mbggenerated
     */
    public Integer getCouponsType() {
        return couponsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.coupons_type
     *
     * @param couponsType the value for pay_order.coupons_type
     *
     * @mbggenerated
     */
    public void setCouponsType(Integer couponsType) {
        this.couponsType = couponsType;
    }
}