package member.card.model;

import java.util.Date;

public class Sign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_time
     *
     * @mbggenerated
     */
    private Date signTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.integral_details
     *
     * @mbggenerated
     */
    private String integralDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.integral
     *
     * @mbggenerated
     */
    private String integral;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public Sign(Integer id, Integer memberId, Short status, Integer count, Date signTime, String integralDetails, String integral) {
        this.id = id;
        this.memberId = memberId;
        this.status = status;
        this.count = count;
        this.signTime = signTime;
        this.integralDetails = integralDetails;
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */
    public Sign() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.id
     *
     * @return the value of sign.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.id
     *
     * @param id the value for sign.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.member_id
     *
     * @return the value of sign.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.member_id
     *
     * @param memberId the value for sign.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.status
     *
     * @return the value of sign.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.status
     *
     * @param status the value for sign.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.count
     *
     * @return the value of sign.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.count
     *
     * @param count the value for sign.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_time
     *
     * @return the value of sign.sign_time
     *
     * @mbggenerated
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_time
     *
     * @param signTime the value for sign.sign_time
     *
     * @mbggenerated
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.integral_details
     *
     * @return the value of sign.integral_details
     *
     * @mbggenerated
     */
    public String getIntegralDetails() {
        return integralDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.integral_details
     *
     * @param integralDetails the value for sign.integral_details
     *
     * @mbggenerated
     */
    public void setIntegralDetails(String integralDetails) {
        this.integralDetails = integralDetails == null ? null : integralDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.integral
     *
     * @return the value of sign.integral
     *
     * @mbggenerated
     */
    public String getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.integral
     *
     * @param integral the value for sign.integral
     *
     * @mbggenerated
     */
    public void setIntegral(String integral) {
        this.integral = integral == null ? null : integral.trim();
    }
}