package member.card.dao;

import java.util.List;
import member.card.model.Integral;
import member.card.model.IntegralExample;
import org.apache.ibatis.annotations.Param;

public interface IntegralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    int countByExample(IntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    int deleteByExample(IntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    int insert(Integral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    int insertSelective(Integral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    List<Integral> selectByExample(IntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    Integral selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Integral record, @Param("example") IntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Integral record, @Param("example") IntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Integral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Integral record);
}