package member.card.dao;

import java.util.List;
import member.card.model.IntegralExchange;
import member.card.model.IntegralExchangeExample;
import org.apache.ibatis.annotations.Param;

public interface IntegralExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    int countByExample(IntegralExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    int deleteByExample(IntegralExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    int insert(IntegralExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    int insertSelective(IntegralExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    List<IntegralExchange> selectByExample(IntegralExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    IntegralExchange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IntegralExchange record, @Param("example") IntegralExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IntegralExchange record, @Param("example") IntegralExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IntegralExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integral_exchange
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IntegralExchange record);
}