package member.card.dao;

import java.util.List;
import member.card.model.RechargeOrder;
import member.card.model.RechargeOrderExample;
import org.apache.ibatis.annotations.Param;

public interface RechargeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int countByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int deleteByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int insert(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int insertSelective(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    List<RechargeOrder> selectByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    RechargeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RechargeOrder record, @Param("example") RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RechargeOrder record, @Param("example") RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RechargeOrder record);
}